"""Sofia MCP bridge — a standalone MCP server exposing a scoped subset of
Sofia's own REST API as tools (homework, calendar events, Drive, meal plan —
deliberately NOT grades, which stay private). Runs as its own container on
its own port, fully isolated from the main app's dependencies (the mcp
package needs a newer Starlette than the main FastAPI app is pinned to).

Every tool call is bridged to the main Sofia app over the private Docker
network via HTTP, authenticated with a shared secret (X-Internal-Token) the
main app generates and persists on the ./data volume this container mounts
read-only — see backend/config.py's _load_or_generate_internal_token() and
backend/auth.py's get_current_user().

Incoming requests to THIS server are gated by a separate public token,
checked as either ?token=... (as requested) or a Bearer header, generated
and persisted the same self-healing way on first run.
"""
import base64
import logging
import os
import secrets

import httpx
from contextlib import asynccontextmanager
from mcp.server.fastmcp import FastMCP
from starlette.applications import Starlette
from starlette.middleware import Middleware
from starlette.middleware.base import BaseHTTPMiddleware
from starlette.requests import Request
from starlette.responses import JSONResponse
from starlette.routing import Mount, Route

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(name)s: %(message)s")
logger = logging.getLogger("sofia-mcp")

DATA_DIR = os.getenv("MCP_DATA_DIR", "/app/data")
SOFIA_API_BASE = os.getenv("SOFIA_API_BASE", "http://sofia:8000/api/v1")
ACT_AS_EMAIL = os.getenv("MCP_ACT_AS_EMAIL", "")  # empty = main app's own MCP_DEFAULT_USER_EMAIL default

INTERNAL_TOKEN_PATH = os.path.join(DATA_DIR, "internal_service_token.txt")
PUBLIC_TOKEN_PATH = os.path.join(DATA_DIR, "mcp_public_token.txt")


def _read_internal_token() -> str:
    # Generated by the main Sofia app (backend/config.py) — this container
    # only ever reads it, so both sides always agree without the secret
    # ever needing to be copied into an env var by hand.
    if not os.path.exists(INTERNAL_TOKEN_PATH):
        raise RuntimeError(
            f"{INTERNAL_TOKEN_PATH} not found — is the main sofia service up and "
            "sharing its ./data volume with this container?"
        )
    with open(INTERNAL_TOKEN_PATH) as f:
        return f.read().strip()


def _load_or_generate_public_token() -> str:
    env_val = os.getenv("MCP_PUBLIC_TOKEN", "")
    if env_val:
        return env_val
    if os.path.exists(PUBLIC_TOKEN_PATH):
        with open(PUBLIC_TOKEN_PATH) as f:
            saved = f.read().strip()
        if saved:
            return saved
    new_token = secrets.token_urlsafe(32)
    os.makedirs(DATA_DIR, exist_ok=True)
    with open(PUBLIC_TOKEN_PATH, "w") as f:
        f.write(new_token)
    return new_token


PUBLIC_TOKEN = _load_or_generate_public_token()
logger.info("Public MCP token file: %s (unchanged across restarts)", PUBLIC_TOKEN_PATH)


def _client() -> httpx.AsyncClient:
    headers = {"X-Internal-Token": _read_internal_token()}
    if ACT_AS_EMAIL:
        headers["X-Act-As-Email"] = ACT_AS_EMAIL
    return httpx.AsyncClient(base_url=SOFIA_API_BASE, headers=headers, timeout=30)


mcp = FastMCP("Sofia", stateless_http=True)

# --- Hausaufgaben ---

@mcp.tool()
async def list_homework() -> list[dict]:
    """Listet alle Hausaufgaben der Klasse auf."""
    async with _client() as c:
        r = await c.get("/homework/")
        r.raise_for_status()
        return r.json()


@mcp.tool()
async def get_homework(homework_id: int) -> dict:
    """Liest eine einzelne Hausaufgabe inklusive Anhängen und Lösungen."""
    async with _client() as c:
        r = await c.get(f"/homework/{homework_id}")
        r.raise_for_status()
        return r.json()


@mcp.tool()
async def create_homework(subject_id: int, description: str, due_date: str) -> dict:
    """Erstellt eine neue Hausaufgabe. due_date im Format YYYY-MM-DD."""
    async with _client() as c:
        r = await c.post("/homework/", json={
            "subject_id": subject_id, "description": description, "due_date": due_date,
        })
        r.raise_for_status()
        return r.json()


@mcp.tool()
async def update_homework(
    homework_id: int,
    description: str | None = None,
    due_date: str | None = None,
    subject_id: int | None = None,
) -> dict:
    """Bearbeitet eine bestehende Hausaufgabe. Nur angegebene Felder werden geändert."""
    body = {k: v for k, v in {
        "description": description, "due_date": due_date, "subject_id": subject_id,
    }.items() if v is not None}
    async with _client() as c:
        r = await c.put(f"/homework/{homework_id}", json=body)
        r.raise_for_status()
        return r.json()


@mcp.tool()
async def delete_homework(homework_id: int) -> dict:
    """Löscht eine Hausaufgabe endgültig."""
    async with _client() as c:
        r = await c.delete(f"/homework/{homework_id}")
        r.raise_for_status()
        return r.json()


# --- Kalender ---

@mcp.tool()
async def list_events(month: str | None = None) -> list[dict]:
    """Listet Kalendertermine auf. month optional im Format YYYY-MM, um auf einen Monat einzugrenzen."""
    async with _client() as c:
        r = await c.get("/calendar/", params={"month": month} if month else None)
        r.raise_for_status()
        return r.json()


@mcp.tool()
async def create_event(
    title: str,
    date: str,
    event_type: str = "other",
    time: str | None = None,
    end_date: str | None = None,
    description: str | None = None,
    subject_id: int | None = None,
) -> dict:
    """Erstellt einen neuen Kalendertermin. date/end_date im Format YYYY-MM-DD, time im
    Format HH:MM. event_type: exam, trip, other, personal oder holiday."""
    async with _client() as c:
        r = await c.post("/calendar/", json={
            "title": title, "date": date, "end_date": end_date, "time": time,
            "event_type": event_type, "description": description, "subject_id": subject_id,
        })
        r.raise_for_status()
        return r.json()


@mcp.tool()
async def update_event(
    event_id: int,
    title: str,
    date: str,
    event_type: str = "other",
    time: str | None = None,
    end_date: str | None = None,
    description: str | None = None,
    subject_id: int | None = None,
) -> dict:
    """Bearbeitet einen bestehenden Kalendertermin. Alle Felder sind wie beim Erstellen
    anzugeben, auch die unveränderten."""
    async with _client() as c:
        r = await c.put(f"/calendar/{event_id}", json={
            "title": title, "date": date, "end_date": end_date, "time": time,
            "event_type": event_type, "description": description, "subject_id": subject_id,
        })
        r.raise_for_status()
        return r.json()


@mcp.tool()
async def delete_event(event_id: int) -> dict:
    """Löscht einen Kalendertermin."""
    async with _client() as c:
        r = await c.delete(f"/calendar/{event_id}")
        r.raise_for_status()
        return r.json()


# --- Drive ---

@mcp.tool()
async def list_drive_files() -> list[dict]:
    """Listet alle Dateien im Drive auf (Metadaten wie Name, Fach, Thema, Größe — kein Inhalt)."""
    async with _client() as c:
        r = await c.get("/drive/")
        r.raise_for_status()
        return r.json()


@mcp.tool()
async def upload_drive_file(
    filename: str,
    content_base64: str,
    subject_id: int | None = None,
    topic: str | None = None,
) -> dict:
    """Lädt eine neue Datei ins Drive hoch. content_base64 ist der Dateiinhalt
    Base64-kodiert. Wird subject_id weggelassen, versucht die KI automatisch
    das passende Fach zu erkennen."""
    raw = base64.b64decode(content_base64)
    async with _client() as c:
        r = await c.post(
            "/drive/upload",
            data={"subject_id": str(subject_id) if subject_id is not None else "", "topic": topic or ""},
            files={"file": (filename, raw)},
        )
        r.raise_for_status()
        return r.json()


@mcp.tool()
async def update_drive_file(file_id: int, subject_id: int | None = None, topic: str | None = None) -> dict:
    """Verschiebt eine Drive-Datei in ein anderes Fach und/oder Thema."""
    async with _client() as c:
        r = await c.put(f"/drive/{file_id}", json={"subject_id": subject_id, "topic": topic})
        r.raise_for_status()
        return r.json()


@mcp.tool()
async def delete_drive_file(file_id: int) -> dict:
    """Löscht eine Datei aus dem Drive."""
    async with _client() as c:
        r = await c.delete(f"/drive/{file_id}")
        r.raise_for_status()
        return r.json()


# --- Essensplan ---

@mcp.tool()
async def get_mealplan() -> dict:
    """Liest den aktuellen Essensplan der Woche inklusive heutigem Gericht."""
    async with _client() as c:
        r = await c.get("/mealplan/current")
        r.raise_for_status()
        return r.json()


@mcp.tool()
async def update_mealplan_day(day_id: int, meal: str) -> dict:
    """Ändert den Eintrag für einen einzelnen Tag im Essensplan (day_id kommt aus get_mealplan)."""
    async with _client() as c:
        r = await c.patch(f"/mealplan/day/{day_id}", json={"meal": meal})
        r.raise_for_status()
        return r.json()


@mcp.tool()
async def delete_mealplan(mealplan_id: int) -> dict:
    """Löscht den kompletten aktuellen Essensplan."""
    async with _client() as c:
        r = await c.delete(f"/mealplan/{mealplan_id}")
        r.raise_for_status()
        return r.json()


@mcp.tool()
async def create_mealplan(image_base64: str) -> dict:
    """Legt einen neuen Essensplan an: ein Foto des wöchentlichen Speiseplans
    (Base64-kodiertes JPEG/PNG) wird hochgeladen, die KI liest daraus
    automatisch eine Tagestabelle aus."""
    raw = base64.b64decode(image_base64)
    async with _client() as c:
        r = await c.post("/mealplan/upload", files={"file": ("mealplan.jpg", raw, "image/jpeg")})
        r.raise_for_status()
        return r.json()


# --- ASGI app: token-gated wrapper around the MCP streamable-HTTP app ---

class TokenAuthMiddleware(BaseHTTPMiddleware):
    async def dispatch(self, request: Request, call_next):
        if request.url.path == "/health":
            return await call_next(request)
        token = request.query_params.get("token")
        if not token:
            auth_header = request.headers.get("Authorization", "")
            if auth_header.startswith("Bearer "):
                token = auth_header[len("Bearer "):]
        if not token or not secrets.compare_digest(token, PUBLIC_TOKEN):
            return JSONResponse({"error": "unauthorized"}, status_code=401)
        return await call_next(request)


async def health(request: Request):
    return JSONResponse({"ok": True})


@asynccontextmanager
async def lifespan(app: Starlette):
    async with mcp.session_manager.run():
        yield


app = Starlette(
    routes=[
        Route("/health", health),
        Mount("/", app=mcp.streamable_http_app()),
    ],
    middleware=[Middleware(TokenAuthMiddleware)],
    lifespan=lifespan,
)
